-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.category
(
    id serial NOT NULL,
    name character varying(50) NOT NULL,
    description text NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public.category
    IS 'Hold all categories available';

CREATE TABLE IF NOT EXISTS public.expense
(
    id serial NOT NULL,
    amount double precision NOT NULL,
    category_id integer NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.expense
    ADD CONSTRAINT category_fk FOREIGN KEY (category_id)
    REFERENCES public.category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;